### ISSUE TITLE
Basic Events File Tools 

### ISSUE THREAD

**Issue by zeroset** [JuPedSim/simulator#17]
Pedestrians in the simulation should be spawned corresponding to a event configuration file. This file can be created using python tooling. 
Implement the tool for generating pedestrian spawn events in the event configuration file. The first tool should create uniform random distributed pedestrians in a spawn area. Command line arguments: which area, how many, distribution.

A suggested example event configuration file could be: 
```json
[
	{
		"t": 0, 
		"event": {
			"type": "spawn_pedestrian",
			"x":22.6,
			"y": -1.5,
			"floor": "groundfloor"
		}
	},
	{
		"t": 1337, 
		"event": {
			"type": "panic"
		}
	},
]
```

**Comment by Ozaq** [comment]
Since we already want to use random numbers here we need to have a look at how python is generating random numbers and applying different distribution functions. In the doc (https://docs.python.org/3/library/random.html) it is written:

>***Notes on Reproducibility***
>
>Sometimes it is useful to be able to reproduce the sequences given by a pseudo-random number generator. By re-using a seed value, the same sequence should be reproducible from run to run as long as multiple threads are not running.
>
>Most of the random module’s algorithms and seeding functions are subject to change across Python versions, but two aspects are guaranteed not to change:
>
> *   If a new seeding method is added, then a backward compatible seeder will be offered.
>
>  *  The generator’s random() method will continue to produce the same sequence when the compatible seeder is given the same seed.

Unfortunately they do not state anything regarding the stability of the distribution functions (see std::random issues).

@schroedtert IIRC you did look into this a bit deeper on the C++ side, do you have any idea what to do on the python side of hings? Id guess we need to look at scipy or numpy but I haven't so far.

**Comment by zeroset** [comment]
Good that i eventually read your edit before answering. Maybe we try to remember this as an option, but i would say it is an input and not that important for reproducibility.
